//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public string cod_equ { get; set; }
        public string nom_equ { get; set; }
    }
}
