//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string cod_usu { get; set; }
        public string nom_usu { get; set; }
        public string email { get; set; }
        public string cod_cla { get; set; }
        public string tip_usu { get; set; }
        public string cod_pais { get; set; }
        public string cod_ubi_geo { get; set; }
        public string dir_usu { get; set; }
        public string num_tlf { get; set; }
        public string nom_ent { get; set; }
        public string cod_equ { get; set; }
    }
}
